### ISSUE TITLE
Can't make iso-numeric.cbx

### ISSUE THREAD

**Issue by tomasvitek** [hroncok/bakalarka#1]
On Mac OSX 10.9.2. :(

```
make: *** No rule to make target `iso-numeric.cbx', needed by `BP_Hroncok_Miroslav_2014.pdf'.  Stop.
```

**Comment by tomasvitek** [comment]
Never mind. :) I knew I should not have posted this and rather try to fix it myself. I didn't pull the repo, but just downloaded it using GitHub and they don't include submodules. Please ignore this. :)

**Comment by hroncok** [comment]
Well, it happens also when you clone it. I wanted to trick it by:

```
%.cbx: biblatex-iso690/%.cbx biblatex-iso690/README
    ln -s "$<" .

biblatex-iso690/README:
    git submodule init
    git submodule update

```

But apparently, the first dependency is being targeted first.

**Comment by hroncok** [comment]
OK, now it says:

```
$ make
(snip)
git submodule init
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make: *** [biblatex-iso690/iso-numeric.cbx] Error 128
```

And that is good enough.
